/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Board.hpp"
#include "SPI_Master.h"
#include "SysTick.h"
#include "FastIo.hpp"

uint32_t millisNow;

FastIo ledPin(BoardPins::Pin::LED);
FastIo wsRstPin(BoardPins::Pin::WZ_RST_N);

const SPI_Master::SPI_Config eepSpiCfg = {
        SPI_Master::Prescaler::DIV_256,
        SPI_Master::SPI_Mode::MODE_0,
        SPI_Master::BitOrder::MSB_FIRST
};

uint8_t test = 0x55;

uint8_t testBuf[256];
size_t testBufSize;

void setup(void)
{
    BRD_init();
    millisNow = SysTick_GetMillis();

    eepIf.init(&eepSpiCfg);

    eepIf.begin();
    modbus.init(1000000);
    wsRstPin.set();
}

int main(void)
{
    setup();

    modbus.freeRxBuffer();
    //Main loop
	for(;;)
	{
	    if(SysTick_GetMillis() - millisNow >= 500)
	    {
	        millisNow = SysTick_GetMillis();
	        if(ledPin.get())
	        {
	            ledPin.clr();
	        }
	        else
	        {
	            ledPin.set();
	            eepIf.write(&test, 1);
	        }
	    }
	            if(modbus.isRxDone())
	            {
	                testBufSize = modbus.isRxAvail();
	                if(testBufSize > 256)
	                    testBufSize = 256;
	                uint8_t * rxBuf = modbus.getRxBuffer();

	                for(size_t i = 0; i < testBufSize; i++)
	                {
	                    testBuf[i] = rxBuf[i];
	                }

	                modbus.freeRxBuffer();
	                modbus.send(testBuf, testBufSize);
	            }






	}
}

extern "C" void NMI_Handler(void)
{
    for(;;);
}

extern "C" void HardFault_Handler(void)
{
    for(;;);
}

